AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - vendor/**/*
    - db/schema.rb
    - config/initializers/pagy.rb
    - bin/bundle
    - bin/yarn
Style/StringLiterals:
  Exclude:
    - config/**/*
Layout/HashAlignment:
  Exclude:
    - lib/**/*
### Metrics ###
Metrics/BlockLength:
  Max: 50
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 100
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 100
