AllCops:
  Exclude:
    - node_modules/**/*
    - vendor/**/*
    - db/schema.rb
    - config/initializers/pagy.rb
    - bin/bundle
    - bin/yarn

Style/StringLiterals:
  Exclude:
    - config/**/*
Layout/HashAlignment:
Documentation:
  Enabled: false
  Exclude:
    - lib/**/*

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 50

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*
